export declare const semiColonString: string;
export declare const singleQuoteString: string;
export declare const escapedDoubleQuotesString: string;
export declare const subkeysJsonKey: string;
export declare const hmlbatSchemaName: string;
export declare const jtrachSchemaName: string;
export declare const databaseClientTable: string;
export declare const databaseQueryCdCliCondition: string;
export declare const databaseQueryCdCliCpaCondition: string;
export declare const databaseQueryCdCliCnpjCondition: string;
export declare const databaseQueryCdCtcelSer: string;
export declare const databaseContagem: string;
export declare const databaseCountAll: string;
export declare const memoryContagem: string;
export declare const devEnvironmentName: string;
export declare const qaEnvironmentName: string;
export declare const sandboxEnvironmentName: string;
export declare const stgEnvironmentName: string;
export declare const stressEnvironmentName: string;
export declare const doubleDashAtStartRegex: RegExp;
export declare const memoryReferenceRegex: RegExp;
export declare const queryValidationRegex: RegExp;
export declare const simpleQuoteDetectionRegex: RegExp;
export declare const defaultTestFolder: string;
export declare const dataFolderString: string;
export declare const dataFilePath: string;
export declare const cpfVariableName: string;
export declare const cnpjVariableName: string;
export declare const nameVariableName: string;
export declare const surnameVariableName: string;
export declare const fullNameVariableName: string;
export declare const emailVariableName: string;
export declare const cellphoneVariableName: string;
export declare const landlineVariableName: string;
export declare const zipcodeVariableName: string;
export declare const addressNumberVariableName: string;
export declare const addressComplementVariableName: string;
export declare const birthdayVariableName: string;
export declare const imeiUpperVariableName: string;
export declare const numberGeneratorMin: number;
export declare const numberGeneratorMax: number;
export declare const minYearBirthday: number;
export declare const maxYearBirthday: number;
export declare const minMonthBirthday: number;
export declare const maxMonthBirthday: number;
export declare const minDayNumber: number;
export declare const shortMonthDayNumber: number;
export declare const longMonthDayNumber: number;
export declare const longerMonthDayNumber: number;
export declare const januaryMonthNumber: number;
export declare const februaryMonthNumber: number;
export declare const marchMonthNumber: number;
export declare const aprilMonthNumber: number;
export declare const mayMonthNumber: number;
export declare const juneMonthNumber: number;
export declare const julyMonthNumber: number;
export declare const augustMonthNumber: number;
export declare const septemberMonthNumber: number;
export declare const octoberMonthNumber: number;
export declare const novemberMonthNumber: number;
export declare const decemberMonthNumber: number;
export declare const twoDigitThreshold: number;
export declare const cellphoneTemplateString: string;
export declare const cellphoneNumberGenerationTarget: number;
export declare const landlineTemplateString: string;
export declare const landlineNumberGenerationTarget: number;
export declare const phoneDigitNumberLimit: number;
export declare function BuildInvalidEnvironmentErrorMessage(incorrectEnvironmentReceived: string): string;
export declare function BuildOnlyNumericString(rawText: string): string;
export declare function BuildClientCpfCondition(cpf: any): string;
export declare function BuildClientCnpjCondition(cnpj: any): string;
export declare function BuildPcsCelQueryCondition(imeiNumber: string): string;
export declare function BuildUnknownMemoryFetchErrorMessage(inputData: string): string;
export declare function BuildEmptyResultQueryErrorMessage(): string;
export declare function BuildInvalidRandomGeneratorOption(options: string[]): string;
export declare function BuildInvalidMonthErrorMessage(): string;
