export declare const protractorCommandTemplate: string;
export declare const protractorDisableChecksFlag: string;
export declare const remoteServerInternalParameter: string;
export declare const seleniumServerHubEndpoint: string;
export declare const webArgumentIndexOffset: number;
export declare const webCucumberTagsParameter: string;
export declare const webHeadlessParameterName: string;
export declare const webRemoteServerParameterName: string;
export declare const webHeadlessCapabilitiesArray: string[];
export declare function BuildJavascriptWebConfigFilesPath(configurationFileName: string): string;
